// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ForeSiteUninstall
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIWeatherfordForeSiteBWindow UIWeatherfordForeSiteBWindow
        {
            get
            {
                if ((this.mUIWeatherfordForeSiteBWindow == null))
                {
                    this.mUIWeatherfordForeSiteBWindow = new UIWeatherfordForeSiteBWindow();
                }
                return this.mUIWeatherfordForeSiteBWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIWeatherfordForeSiteBWindow mUIWeatherfordForeSiteBWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIWeatherfordForeSiteBWindow : WpfWindow
    {
        
        public UIWeatherfordForeSiteBWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Weatherford ForeSite Bundle";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Weatherford ForeSite Bundle");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MaintenanceWelcomePage";
            this.WindowTitles.Add("Weatherford ForeSite Bundle");
            #endregion
        }
        
        #region Properties
        public WpfButton UIUninstallAllButton
        {
            get
            {
                if ((this.mUIUninstallAllButton == null))
                {
                    this.mUIUninstallAllButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIUninstallAllButton.SearchProperties[WpfButton.PropertyNames.Name] = "Uninstall All";
                    this.mUIUninstallAllButton.WindowTitles.Add("Weatherford ForeSite Bundle");
                    #endregion
                }
                return this.mUIUninstallAllButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIUninstallAllButton;
        #endregion
    }
}
