//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumAutomation.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumAutomation.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acidize - Coiled Tubing.
        /// </summary>
        internal static string acidizecoileventtype {
            get {
                return ResourceManager.GetString("acidizecoileventtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acidize.
        /// </summary>
        internal static string acidizeeventtype {
            get {
                return ResourceManager.GetString("acidizeeventtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        internal static string American_serviceprovider {
            get {
                return ResourceManager.GetString("American_serviceprovider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellbore Hole OD- 2.0000.
        /// </summary>
        internal static string catlgitemdesc {
            get {
                return ResourceManager.GetString("catlgitemdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string compdepth {
            get {
                return ResourceManager.GetString("compdepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string complength {
            get {
                return ResourceManager.GetString("complength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comp1.
        /// </summary>
        internal static string compname {
            get {
                return ResourceManager.GetString("compname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borehole.
        /// </summary>
        internal static string component {
            get {
                return ResourceManager.GetString("component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor Casing.
        /// </summary>
        internal static string component1 {
            get {
                return ResourceManager.GetString("component1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        internal static string continuous {
            get {
                return ResourceManager.GetString("continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Steaming.
        /// </summary>
        internal static string currentlysteaming {
            get {
                return ResourceManager.GetString("currentlysteaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200.
        /// </summary>
        internal static string drillingreporttime {
            get {
                return ResourceManager.GetString("drillingreporttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10012018.
        /// </summary>
        internal static string eventbegindate {
            get {
                return ResourceManager.GetString("eventbegindate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120000.
        /// </summary>
        internal static string eventbegintime {
            get {
                return ResourceManager.GetString("eventbegintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10042018.
        /// </summary>
        internal static string eventchangebegindate {
            get {
                return ResourceManager.GetString("eventchangebegindate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12252018.
        /// </summary>
        internal static string eventenddate {
            get {
                return ResourceManager.GetString("eventenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120000.
        /// </summary>
        internal static string eventendtime {
            get {
                return ResourceManager.GetString("eventendtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11012018.
        /// </summary>
        internal static string futuredate {
            get {
                return ResourceManager.GetString("futuredate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string inprogress {
            get {
                return ResourceManager.GetString("inprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04262019.
        /// </summary>
        internal static string jobcostdate {
            get {
                return ResourceManager.GetString("jobcostdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellbore Hole.
        /// </summary>
        internal static string parttype {
            get {
                return ResourceManager.GetString("parttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casing Hanger.
        /// </summary>
        internal static string parttype1 {
            get {
                return ResourceManager.GetString("parttype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        internal static string planned {
            get {
                return ResourceManager.GetString("planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string scheduled {
            get {
                return ResourceManager.GetString("scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam-Midpoint.
        /// </summary>
        internal static string steammidpoint {
            get {
                return ResourceManager.GetString("steammidpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam-Put on Production.
        /// </summary>
        internal static string steamputonproduction {
            get {
                return ResourceManager.GetString("steamputonproduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam-Soak.
        /// </summary>
        internal static string steamsoak {
            get {
                return ResourceManager.GetString("steamsoak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Sheet Complete.
        /// </summary>
        internal static string toursheetcomplete {
            get {
                return ResourceManager.GetString("toursheetcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alten.
        /// </summary>
        internal static string vendor {
            get {
                return ResourceManager.GetString("vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on AFE.
        /// </summary>
        internal static string waitingafe {
            get {
                return ResourceManager.GetString("waitingafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on Approval.
        /// </summary>
        internal static string waitingapproval {
            get {
                return ResourceManager.GetString("waitingapproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on External System.
        /// </summary>
        internal static string waitingexternal {
            get {
                return ResourceManager.GetString("waitingexternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on Maintenance.
        /// </summary>
        internal static string waitingmaintenance {
            get {
                return ResourceManager.GetString("waitingmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on Tour Sheet.
        /// </summary>
        internal static string waitingontoursheet {
            get {
                return ResourceManager.GetString("waitingontoursheet", resourceCulture);
            }
        }
    }
}
